// src/components/adminStyles.ts
export const styles = {
    container: { display: 'flex', minHeight: '100vh', backgroundColor: '#f8fafc', fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif' },
    sidebar: { width: '260px', backgroundColor: '#0f172a', padding: '30px 20px', display: 'flex', flexDirection: 'column' as const },
    logo: { color: '#fff', fontSize: '20px', fontWeight: 'bold' as const, marginBottom: '40px', textAlign: 'center' as const, letterSpacing: '1px' },
    menuItem: { padding: '14px 20px', color: '#94a3b8', textDecoration: 'none', borderRadius: '8px', marginBottom: '8px', fontWeight: '500', display: 'block' },
    menuActive: { padding: '14px 20px', color: '#fff', backgroundColor: '#3b82f6', textDecoration: 'none', borderRadius: '8px', marginBottom: '8px', fontWeight: '600', display: 'block' },
    sidebarFooter: { marginTop: 'auto', color: '#475569', fontSize: '12px', textAlign: 'center' as const },
    mainContent: { flex: 1, padding: '40px', overflowY: 'auto' as const },
    header: { marginBottom: '32px' },
    title: { fontSize: '26px', color: '#0f172a', fontWeight: '700' as const, margin: '0 0 6px 0' },
    subtitle: { fontSize: '14px', color: '#64748b', margin: 0 },
    card: { backgroundColor: '#fff', padding: '26px', borderRadius: '12px', boxShadow: '0 1px 3px rgba(0,0,0,0.05), 0 1px 2px rgba(0,0,0,0.05)', marginBottom: '20px' },
    formGroup: { marginBottom: '20px' },
    label: { display: 'block', fontSize: '14px', fontWeight: '600' as const, color: '#334155', marginBottom: '8px' },
    select: { width: '100%', padding: '11px', borderRadius: '8px', border: '1px solid #cbd5e1', fontSize: '14px', outline: 'none', color: '#334155', backgroundColor: '#fff' },
    textarea: { width: '100%', height: '140px', padding: '12px', borderRadius: '8px', border: '1px solid #cbd5e1', fontSize: '13px', fontFamily: 'monospace', outline: 'none', resize: 'vertical' as const },
    submitBtn: { width: '100%', padding: '13px', backgroundColor: '#10b981', color: '#fff', border: 'none', borderRadius: '8px', fontSize: '14px', fontWeight: 'bold' as const, cursor: 'pointer', transition: 'background 0.2s' },
    refreshBtn: { padding: '8px 14px', backgroundColor: '#f1f5f9', color: '#475569', border: '1px solid #e2e8f0', borderRadius: '6px', fontSize: '13px', fontWeight: '500' as const, cursor: 'pointer' },
    alertSuccess: { padding: '12px', backgroundColor: '#d1fae5', color: '#065f46', borderRadius: '8px', marginBottom: '15px', fontSize: '14px', fontWeight: '500' as const },
    alertError: { padding: '12px', backgroundColor: '#fee2e2', color: '#991b1b', borderRadius: '8px', marginBottom: '15px', fontSize: '14px', fontWeight: '500' as const },
    table: { width: '100%', borderCollapse: 'collapse' as const },
    thRow: { backgroundColor: '#f8fafc' },
    th: { padding: '12px 16px', color: '#64748b', fontWeight: '600' as const, borderBottom: '1px solid #e2e8f0', fontSize: '13px', textAlign: 'left' as const },
    trEven: { backgroundColor: '#fff' },
    trOdd: { backgroundColor: '#fafafa' },
    tdBold: { padding: '14px 16px', color: '#0f172a', fontWeight: '600' as const, borderBottom: '1px solid #e2e8f0', fontSize: '14px' },
    tdCount: { padding: '14px 16px', color: '#ef4444', fontWeight: 'bold' as const, borderBottom: '1px solid #e2e8f0', fontSize: '14px' },
    tdBadge: { padding: '14px 16px', borderBottom: '1px solid #e2e8f0' },
    td: { padding: '14px 16px', color: '#475569', borderBottom: '1px solid #e2e8f0', fontSize: '14px' },
    badge: { padding: '4px 8px', backgroundColor: '#e0f2fe', color: '#0369a1', borderRadius: '4px', fontSize: '12px', fontWeight: 'bold' as const },
    statusHigh: { padding: '4px 8px', backgroundColor: '#fee2e2', color: '#991b1b', borderRadius: '4px', fontSize: '12px', fontWeight: 'bold' as const },
    statusNormal: { padding: '4px 8px', backgroundColor: '#f1f5f9', color: '#475569', borderRadius: '4px', fontSize: '12px', fontWeight: '500' as const },
};